import './globals.css';
import React from 'react';

export const metadata = {
	title: 'Geometry tests',
	description: 'Generated by Next.js',
};

export default async function RootLayout({
	children,
}) {
	return (
		<html lang="en">
		<body>
		{children}
		</body>
		</html>
	);
}
