import React from 'react';

export const metadata = {
	title: 'Landing for math tests',
	description: 'Generated by Next.js',
};

export default async function MathLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
		<body>
		<div className={`bg-background grid gap-y-0 overflow-hidden`}>
			<div className={`relative bg-background flex items-center flex-col`}>
				<div className="max-w-3xl mx-auto">
					<main className="mt-4 mx-auto max-w-3xl px-4 sm:mt-12 sm:px-6 md:mt-4 lg:mt-4 lg:px-8 xl:mt-4">
						<div className="sm:text-left lg:text-left">
							{children}
						</div>
					</main>
				</div>
			</div>
		</div>
		</body>
		</html>
	);
}
